name: Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  DOCKER_IMAGE_NAME: 'cosmosdb-python-fastapi'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{DOCKER_IMAGE_NAME}}':$(date +%s)
